name: Build and deploy to Azure Functions
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './.'
          dotnet build Main/NextBuses.csproj --configuration Release --output ./output/NextBuses/
          popd
      - name: 'Deploy Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: CatchThatBus
          package: ./output/NextBuses
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
